AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CalculatorFunction:
    Type: AWS::Serverless::Function
    Properties: 
      Handler: calculator.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 60
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
Outputs:
  CalculatorFunctionApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
